name: simonoshea
favicon: null
layout_spectrum: 0.73367
typography_spectrum: 0.85223
title: The Reflection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a2a4a3'
    - '#000000'
    - '#56596a'
    - '#018a68'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
